### ISSUE TITLE
This plugin supports only python based MLs. Need to update the docs.

### ISSUE THREAD

**Issue by sergeydyshlevyi** [dataiku/dss-plugin-model-drift#11]
Based on support ticket https://support.dataiku.com/a/tickets/21640 where the customer had issues using this plugin with MLlib (no collector_data.json file created), we need to update the docs informing others this plugin supports only python based ML.

**Comment by du-phan** [comment]
Closed as this is now mentioned in the [doc](https://www.dataiku.com/product/plugins/model-drift/)
